# Generated by Django 5.1.7 on 2025-03-11 15:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='estado',
            field=models.CharField(default='pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
